import type { Metadata } from 'next';
import { Nunito, Nunito_Sans } from 'next/font/google';
import './globals.css';
import { getServerSession } from 'next-auth';
import { ThemeProvider } from 'next-themes';
import GlobalHeader from '@/components/header';
import SessionProviderClient from './components/SessionProviderClient';

const getNunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
});

const getNunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${getNunito.variable} ${getNunitoSans.variable} antialiased font-nunito-sans font-nunito `}>
        <SessionProviderClient session={session}>
          <ThemeProvider attribute="class" defaultTheme="light" forcedTheme="light" disableTransitionOnChange>
            <main>
              {session?.user && (
                <section>
                  <GlobalHeader />
                </section>
              )}
              <section>{children}</section>
            </main>
          </ThemeProvider>
        </SessionProviderClient>
      </body>
    </html>
  );
}

